### PR TITLE
fix: inline entity form errors

### PR DESCRIPTION
**Pull request by ccjjmartin**

### CODE REVIEW

**Comment by ccjjmartin** [comment]
@callinmullaney @rebecaescandon This fixes the inline entity form error for me

**Review by callinmullaney — APPROVED** [review]
Based `better-entity-browsers-3` off this branch. Definitely fixed the inline entity form error during the install :tada:

**Comment by ccjjmartin** [comment]
@callinmullaney Sounds great, I will merge this one into yours.

**Pull request merged**
