### PR TITLE
Change the admin theme to Gin and remove Claro

### PR DESCRIPTION
**Pull request by Gregg-Hendrix**
This PR does the following:

- Removed support for the [Claro Admin theme](https://www.drupal.org/project/claro/)
- Installs the [Gin admin theme](https://www.drupal.org/project/gin)

Notes:

- Gin is a new core theme with a rigorously tested design system: https://www.drupal.org/docs/8/core/themes/gin-theme/design.
- Accessibility is a driving focus of gin.
- The color palette is fairly neutral.
- Support and bug fixes will be bundled with core updates.

### CODE REVIEW

**Comment by Gregg-Hendrix** [comment]
image

**Comment by callinmullaney** [comment]
@Gregg-Hendrix This looks good to me! One small change we'll need in the other repo in order to consider this complete. 

- checkout the [sous-drupal-project](https://github.com/fourkitchens/sous-drupal-project) and switch your branch to 4.x-beta. 
- Create a new branch with the same name as this one.
- Update this line to gin - https://github.com/fourkitchens/sous-drupal-project/blob/2.x/sous/Starter.php#L32 
- Create a PR with this change and tag me.

Once that is complete we should be in a good spot to merge these and have a fully updated install.

**Review by callinmullaney — APPROVED** [review]
👏 Good to go for the 4.x release

**Pull request merged**
